//actions
const actions = {
  ADD_EXPENSE_ITEM: "ADD_EXPENSE_ITEM",
  EDIT_EXPENSE_ITEM: "EDIT_EXPENSE_ITEM",
  DELETE_EXPENSE_ITEM: "DELETE_EXPENSE_ITEM",
  CLEAR_EXPENSE_ITEM: "CLEAR_EXPENSE_ITEM",
};

export { actions };
